---
version: 0.1
runson: linux
autosplit: true

maxRetries: 5
concurrency: 2

# Dependency caching for Windows
cacheKey: '{{ checksum "requirements.txt" }}'
cacheDirectories:
  - CacheDir
pre:
  - pip3 install -r requirements.txt --cache-dir CacheDir

testDiscovery:
  type: raw
  mode: dynamic
  command: grep -nri 'HyperTestPyUnit' tests -ir --include=*.py | sed 's/:.*//'

testRunnerCommand: python3 -s $test
  
